#!/usr/bin/env python

import os
import re
import subprocess
import sys
import tempfile


def run(cmd):
    print("----------------------------------------------------------------------")
    print("# %s" % cmd)
    print("----------------------------------------------------------------------")
    if os.system(cmd) != 0:
        raise Exception(cmd)


# https://blog.codinghorror.com/sorting-for-humans-natural-sort-order
def sort_human(l):
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    l.sort(key=alphanum_key)


run("git fetch --tags")

# get latest tag
tags = ["cleverbuild-0"]
for line in subprocess.Popen("git tag".split(), stdout=subprocess.PIPE).communicate()[0].splitlines():
    tag = os.path.basename(line)
    if "cleverbuild" in tag:
        tags.append(tag)
sort_human(tags)
tag = tags[-1]

build_number = int(re.findall("[0-9]+", tag)[-1])
os.environ["CLEVERBUILD_NUMBER"] = str(build_number)

# work_tree
work_tree = tempfile.mkdtemp()
run("git archive %s | tar -x -C %s" % (tag, work_tree))

# run cleverbuild
cleverbuild = "./cleverbuild"
run("cd %s && if [ -f %s ]; then %s; fi" % (work_tree, cleverbuild, cleverbuild))

# run cleverscript
cleverscript = "./cleverscript"
if len(sys.argv) > 1:
    cleverscript += "-%s" % sys.argv[1]
run("cd %s && if [ -f %s ]; then %s; fi" % (work_tree, cleverscript, cleverscript))

run("echo %s" % tag)
