#!/usr/bin/env python

import re
import sys

# https://blog.codinghorror.com/sorting-for-humans-natural-sort-order
def sort_human(l):
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    l.sort(key=alphanum_key)

lines = sys.stdin.read().splitlines()
sort_human(lines)
for line in lines:
    print line
